"""Execute every .sql file against the sample DB, print results, and snapshot them.

Pure standard library (``sqlite3`` + ``csv``) — no third-party dependencies to
run the analytics. Each query's full result is written to ``outputs/results/``
as CSV, and a combined Markdown digest to ``outputs/results.md``.
"""
import csv
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DB = ROOT / "shop.db"
QUERIES = ROOT / "queries"
OUT = ROOT / "outputs"
RESULTS = OUT / "results"

PREVIEW_ROWS = 12   # rows echoed to the console per query


def run_all() -> None:
    if not DB.exists():
        raise SystemExit("Run: python build_db.py first")
    RESULTS.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB)
    digest = ["# Query results\n", "_Generated by `run_queries.py`._\n"]

    for sql_file in sorted(QUERIES.glob("*.sql")):
        sql = sql_file.read_text()
        cur = con.execute(sql)
        cols = [c[0] for c in cur.description]
        rows = cur.fetchall()

        print("\n" + "=" * 72)
        print(f"QUERY: {sql_file.name}   ({len(rows)} rows)")
        print("=" * 72)
        print(" | ".join(cols))
        for row in rows[:PREVIEW_ROWS]:
            print(" | ".join(str(v) for v in row))
        if len(rows) > PREVIEW_ROWS:
            print(f"... (+{len(rows) - PREVIEW_ROWS} more rows)")

        # Full CSV snapshot
        with (RESULTS / f"{sql_file.stem}.csv").open("w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(cols)
            w.writerows(rows)

        # Markdown digest (first PREVIEW_ROWS rows)
        title = sql.splitlines()[0].lstrip("- ").strip()
        digest.append(f"\n## `{sql_file.name}`\n\n{title}\n")
        digest.append("| " + " | ".join(cols) + " |")
        digest.append("|" + "|".join("---" for _ in cols) + "|")
        for row in rows[:PREVIEW_ROWS]:
            digest.append("| " + " | ".join(str(v) for v in row) + " |")

    con.close()
    (OUT / "results.md").write_text("\n".join(digest) + "\n")
    print(f"\nCSV snapshots -> {RESULTS}/   ·   digest -> {OUT / 'results.md'}")


if __name__ == "__main__":
    run_all()
